### ISSUE TITLE
Add blocked state check middleware

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/website#11]
for now users can be blocked or unblocked in the backend. We need to add an middleware instance to check the state.

**Comment by elchroy** [comment]
Hi @Tjoosten . I would like to try this out

**Comment by Tjoosten** [comment]
Sure u can find the role in the permission seeder.

al pr's need to be against the develop branch

**Comment by elchroy** [comment]
HI @Tjoosten . Would you throw more insight on what you expect to be fixed in this issue. 
I would appreciate a scenario where the middleware would come into play.
Or is it more like a custom Validator|Request?

**Comment by Tjoosten** [comment]
Users can log in into the plaform. But they are roles connected tgo the user. Active and blocked. 

If the user is blocked they need to logout again with a flash session. That says they have no permission and that they are blocked. 
If login they can into the backend. _

**Comment by Tjoosten** [comment]
@tjoosten = **NOTE TO MYSELF** needs review.

**Comment by andela-celisha-wigwe** [comment]
What is attemptin a field event is known as what

**Comment by Tjoosten** [comment]
How u mean?

**Comment by elchroy** [comment]
Ignore my last comment. (*deleted). @Tjoosten
