### ISSUE TITLE
Add contributing note to the readme. 

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/website#15]

**Comment by minibhati93** [comment]
I want to work on this. Can I help?

**Comment by Tjoosten** [comment]
Sure. All commits needs to be done at the develop branch.

**Comment by minibhati93** [comment]
Thanks. Are there any guidelines that I should follow?

**Comment by Tjoosten** [comment]
Your free of choice for this. Let yourself go :)

**Comment by Tjoosten** [comment]
@minibhati93 note there is already a contributing file in the repo. In the readme it only to point at it.
