### ISSUE TITLE
Render news items out of the database to the front-end

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/website#20]

**Comment by haakym** [comment]
Happy to make a PR for this, but I'm a little confused with your project structure as it relates to route/controller and view structure and how this is managed between front-end and back-end.

There's already a `NewsController` and `views\news\index.blade.php` which primarily appears to deal with "admin" back-end related stuff. Did you have something in mind for where the news items for the front-end were to be managed via a controller and view (perhaps I'm missing something) or does the project need some restructuring?

I'd see your project being more structured if the views, routes and controllers were all split into separate back-end and front-end folders/urls/namespaces. Again, perhaps I'm missing something.

Please advise! Thank you!

**Comment by Tjoosten** [comment]
news on the front-end. There is already a mockup (static)
