### ISSUE TITLE
TravisCI fails

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/website#24]
https://travis-ci.org/Tjoosten/website/builds/166889641 

TravisCI fails. Because there is a mysql issue there. We need to fix it.

**Comment by xRahul** [comment]
Hey @Tjoosten 

The issue seems to be that your travisCI script creates a sqlite file, but your laravel app uses mysql as the database resulting in the error. I'll see to it!

**Comment by Tjoosten** [comment]
PR for this are welcome.

**Comment by xRahul** [comment]
Hey @Tjoosten 

I've fixed the mysql/sqlite error, but there are errors in phpunit testing-
https://travis-ci.org/xRahul/website/jobs/166941368
can you help out with them?!

**Comment by Tjoosten** [comment]
The phpunit errors are ok. you can PR the fix.

**Comment by xRahul** [comment]
PR created- https://github.com/Tjoosten/website/issues/27
