### ISSUE TITLE
[Insight] Text files should end with a newline character - in readme.md, line 26

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/website#52]
**[in readme.md, line 26](https://github.com/Tjoosten/website/blob/4080183ff7624285b95d092b4c4eea6971f64b8c/readme.md#L26)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
## License

The Sijot website is open-sourced software licensed under the [MIT license](http://opensource.org/licenses/MIT).

## Contributing
Contributions are highly appreciated. Please read the [contribution guidelines](contributing.md) here.
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/d897334a-3d17-4888-aa39-29fbbe55fb5d/analyses/1)_

**Comment by varanauskas** [comment]
I'm on it
